cpu {
	direction: down

	if: "IF"

	dmem: "DMem"

	lsu: "LSU" {
		ldq: "LDQ"
		tlb: "TLB"
	}

	core: "Core" {
		rob: "ROB"
		exe: "EXE" {
			addrcalc: "Addr. Gen."
			int0: "Int."
			int1: "Int."
		}

		wb: "WB"
		intq: "Int. Q."
		memq: "Mem. Q."

		wb -> intq
		wb -> memq

		intq -> exe.int0
		intq -> exe.int1

		memq -> exe.addrcalc

	}

	rfp: "RFP" {
		mem: "Mem" {
			banks: "" {
				grid-rows: 4
				grid-columns: 3
				grid-gap: 0

				h0: "Prev" {height: 50}
				h1: "Stride" {height: 50}
				h2: "Confidence" {height: 50}

				e00: "" { height: 20 }
				e01: "" { height: 20 } 
				e02: "" { height: 20 }
				
				e10: "" { height: 20 }
				e11: "" { height: 20 }
				e12: "" { height: 20 }

				e20: "" { height: 20 }
				e21: "" { height: 20 } 
				e22: "" { height: 20 }
				
				e30: "" { height: 20 }
				e31: "" { height: 20 }
				e32: "" { height: 20 }

				e40: "" { height: 20 }
				e41: "" { height: 20 } 
				e42: "" { height: 20 }
				
				e50: "" { height: 20 }
				e51: "" { height: 20 }
				e52: "" { height: 20 }

				e60: "" { height: 20 }
				e61: "" { height: 20 }
				e62: "" { height: 20 }
			}
		}

		br0: "Bank Read 0"
		br0 <> mem
		br0 <> mem
		br0 <> mem
		br0 <> mem

		br1: "Bank Read 1"
		br1 <> mem
		br1 <> mem
		br1 <> mem
		br1 <> mem

		bw: "Bank Write"
		bw <> mem
		bw <> mem
		bw <> mem
		bw <> mem

		tl: "Training Logic"
		tl <> bw
		tl <> bw
		tl <> br1
		tl <> br1

		pl: "Prediction Logic"
		pl <> br0
		pl <> br0
	}

	rfp.pl -> lsu: "Selected Prediction"

	lsu -> dmem: "DMem. Req."
	dmem -> lsu.ldq: "Predicted Value"

	if -> rfp.pl: Enqueued uOPs
	if -> rfp.pl

	if -> core.intq
	if -> core.memq

	if -> core.rob
	if -> core.rob

	core.rob -> rfp.tl: Committed uOPs
	core.rob -> rfp.tl

	lsu -> core.wb

	core.exe.addrcalc -> lsu.tlb: "Addr. Gen."
}
